export const countries = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "New Zealand",
  "Ireland",
  "Nigeria",
  "Ghana",
  "Kenya",
  "South Africa",
  "India",
  "Pakistan",
  "United Arab Emirates",
  "Saudi Arabia",
  "Germany",
  "France",
  "Netherlands",
  "Spain",
  "Italy",
  "Portugal",
  "Sweden",
  "Norway",
  "Switzerland",
  "Poland",
  "Brazil",
  "Mexico",
  "Jamaica",
  "Trinidad and Tobago",
  "Philippines",
  "Singapore",
  "Malaysia",
  "Japan",
  "South Korea",
  "China",
  "Other",
] as const;
